### ISSUE TITLE
old syntax for @pytask.mark.latex

### ISSUE THREAD

**Issue by omererhanerbis** [OpenSourceEconomics/econ-project-templates#106]
OS: MacOS-ARM
Python: 3.9.12
Anaconda: 22.9.0
pytask: 0.2.5
pluggy: 1.0.0

<img width="570" alt="Screen Shot 2022-10-13 at 10 39 36" src="https://user-images.githubusercontent.com/65853744/195546998-dbe0fef3-e2f7-4d0e-90f5-b00abf744cf0.png">

https://econ-project-templates.readthedocs.io/en/stable/getting_started.html#preparing-your-system - Configuring your new project - 5. - pytask run error

**Comment by hmgaudecker** [comment]
Thanks! 

Yes, this is why we fixed pytask < 0.2 in [0.5.2](https://github.com/OpenSourceEconomics/econ-project-templates/releases/tag/v0.5.2)

Working on a big update right now, should be out before the end of the month.
