### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by hmgaudecker** [OpenSourceEconomics/econ-project-templates#110]
- [x] Split up getting started section into gettting started / guides & explanations
- [ ] Check whether list of cookiecutter steps (julia, stata currently supported? other things up-to-date?)
- [x] Explain "Installing additional packages" by updating `environment.yml` rather than `conda install`
- [x] Check list of pre-commit hooks (also sync with https://github.com/pytask-dev/cookiecutter-pytask-project) and formatting (some explanations seem boldface)
- [ ] Go through documentation section concerning the example project
- [ ] Fix Programming languages (what can we realistically support soonish?)

**Comment by hmgaudecker** [comment]
@timmens, would you be so kind to take care of items 2, 3, 4 above at some point? Thanks

**Comment by timmens** [comment]
@hmgaudecker

2. Currently only the Python example is supported. PR #105 adds support for R. Other than that we could discuss whether readthedocs should still be supported. The default Python version could be set to 3.10. Do you want me to update the default Python version and raise an Error if an unsupported language is selected?
3. Are you sure we should redo only this subsection? I think it could make sense to recommend only using environment.yml files and not even introduce the other techniques.
4. I removed the bold formatting. The inner project uses 33 hooks. Are you sure that we want to provide a description for all of them? Or should we explain maybe 3-4 important ones and then link to the documentation of the others?

**Comment by hmgaudecker** [comment]
> Currently only the Python example is supported. PR [Translate example to R #105](https://github.com/OpenSourceEconomics/econ-project-templates/pull/105) adds support for R. Other than that we could discuss whether readthedocs should still be supported. The default Python version could be set to 3.10. Do you want me to update the default Python version and raise an Error if an unsupported language is selected?

- Python 3.10: Yes please, I somehow missed that.
- No readthedocs anymore, see below *(unless you meant something else here?)*
- Probably for now, we should say that the example is in Python, pytask supports `x` $\in \left[\text{R}, \text{Julia}, \text{Stata}\right]$ and that when selecting other languages, only `pytask-{x}` is added to the environment. Worked-out R example is in the making, help on others appreciated. Does that sound sensible?

> Are you sure we should redo only this subsection? I think it could make sense to recommend only using environment.yml files and not even introduce the other techniques.

That was my suggestion, I think, or are you suggesting to remove the option from cookiecutter, so to always create an environment?
 
> I removed the bold formatting. The inner project uses 33 hooks. Are you sure that we want to provide a description for all of them? Or should we explain maybe 3-4 important ones and then link to the documentation of the others?

What do you mean with "link to the documentation" -- where else if not that section?

> **General question**: Do you want the templates to support a readthedocs style documentation? Personally, I think for most research projects a well-structured GitHub repository plus good README is enough. I guess having the option in the cookiecutter spec is not a problem, but I'm not sure how much sense they make for the example project.

We decided to close #103 by removing the inner project documentation -- so yes, seems like a good point to deviate from https://github.com/pytask-dev/cookiecutter-pytask-project/blob/main/cookiecutter.json

**Comment by timmens** [comment]
Okay, I think we agree on all points except for the pre-commit one. What I meant was that on the template documentation we briefly explain pre-commit hooks in general and explain maybe 3-4 ones in detail. We then link to the official [pre-commit docs](https://pre-commit.com/index.html) and maybe to the config file we're using. Then anyone who's interested in understanding what a specific hook is doing can follow the pre-commit docs to get an official description from the authors of that specific hook. Sorry, I was overloading the word "documentation" in my original comment...

**Comment by hmgaudecker** [comment]
Ah, sorry, I messed up. For whatever reason, I thought about the list of choices to make while cutting cookies rather than the hooks. Your suggestion is perfect, maybe just give a couple of easy examples (yaml syntax, git conflict markers, black ?) and focus on the intuition of what is happening. 

Much of the current stuff is outdated, in the old days there was an option to select intrusive/non-intrusive hooks, now everything is done automatically.
