### ISSUE TITLE
Python 3.12 raises InvalidPythonVersionError

### ISSUE THREAD

**Issue by buddejul** [OpenSourceEconomics/econ-project-templates#148]
I got the following error when trying to install a project with `python_version` set to `3.12` in the dialogue.

```console
Traceback (most recent call last):
  File "C:\Users\budde\AppData\Local\Temp\tmp25i07k49.py", line 68, in <module>
    main()
  File "C:\Users\budde\AppData\Local\Temp\tmp25i07k49.py", line 64, in main
    raise InvalidPythonVersionError(python_version)
__main__.InvalidPythonVersionError:
ERROR: The python version must be >= 3.11, got 3.12.

ERROR: Stopping generation because pre_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```

**Comment by hmgaudecker** [comment]
Can you run `pre-commit autoupdate` and try again?

**Comment by buddejul** [comment]
I am sorry, I don't follow: I am in my projects folder (not a git repo) and use 
```
cookiecutter https://github.com/OpenSourceEconomics/econ-project-templates/archive/v0.7.1.zip

**Comment by hmgaudecker** [comment]
Sorry, my bad! Thought it was a pre-commit error, but obviously not. I likely won't be able to take a look before Monday.

**Comment by buddejul** [comment]
Not pressing from my side I am happy to run with the 3.11 option, just wanted to report since the message suggested it should technically be allowed.
