### ISSUE TITLE
BUG: pdbpp instead of pdbp in environment preventing pytask debugging

### ISSUE THREAD

**Issue by buddejul** [OpenSourceEconomics/econ-project-templates#157]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of template_project.

#### Problem description

Discovered while trying to debug using pytask:
- First, `pdb` is set as the default debugger in `pyproject.toml` but it's not included in the environment; pdbpp is, however.
- After adding pdb, setting breakpoints in tasks and using pytask results in infinite terminal output involving pyreadline, a dependency of pdbpp. pytest for some reason doesn't have the issue.

#### Potential solution
Just replace pdbpp by pdbp (via pip I think) - probably what was intended to begin with?

**Comment by hmgaudecker** [comment]
Thanks, very good catch! @timmens, could you have a look?
