### ISSUE TITLE
Stata branch fails with custom Stata starting directory

### ISSUE THREAD

**Issue by felixpoege** [OpenSourceEconomics/econ-project-templates#20]
When running a fresh template of the Stata branch with a Stata installation that uses a custom starting directory (Changing the path in a profile.do), then waf fails. The reason is that the "include project_paths" line cannot be executed, the file is not found. It is a minor irritation, but maybe it would be possible to write code which detects that behavior through running a polit .do file which just checks the current path and if it is not the waf directory, throws a message notifying the user of the problem. A more thorough solution would be to reset the Stata path in every .do file.

**Comment by hmgaudecker** [comment]
Fixes for idiosyncratic installations are always welcome :-)

**Comment by hmgaudecker** [comment]
Not doing any adopath-foo anymore with pytask, so it has become irrelevant with version 0.4
