### ISSUE TITLE
Improvement of automatically generated DAGs

### ISSUE THREAD

**Issue by hmgaudecker** [OpenSourceEconomics/econ-project-templates#40]
* add source files, e.g. schelling.py 
* Different colour for task names.

**Comment by hmgaudecker** [comment]
Tobias originally set that up, maybe coordinate with him.

**Comment by hmgaudecker** [comment]
Some updates in dbe58e2 -- please distribute that version of ``project_dependency_graph.py`` to all flavours and move this to the documentation directory (we probably need to make sure it runs last then).

**Comment by hmgaudecker** [comment]
Sort-of related: Further update in a868ba2, I needed to set shell=True to find pre-commit in the tests. If that does not work on Windows, we'll need a case distinction.

**Comment by raholler** [comment]
> 
> 
> Sort-of related: Further update in [a868ba2](https://github.com/hmgaudecker/econ-project-templates/commit/a868ba2209c7758acd4083f01dcf3265cc056b5a), I needed to set shell=True to find pre-commit in the tests. If that does not work on Windows, we'll need a case distinction.

not an issue.

**Comment by hmgaudecker** [comment]
This would be a nice task for somebody who wants to deepen his or her knowledge of (python-)graphviz and potentially Waf.

Personally, I think it is usable enough for now, though not good enough to replace the manually created examples in the docs, which would be the ultimate goal.

It would also be nice to use something interactive (bokeh & friends) so it becomes useful in serious projects. I do not want to browse a png with many hundreds of tasks.

**Comment by hmgaudecker** [comment]
Irrelevant with pytask or it will be solved at some point on the pytask side. 

Hint, hint, @tobiasraabe :wink:
