### ISSUE TITLE
Feature: Path management Latex

### ISSUE THREAD

**Issue by raholler** [OpenSourceEconomics/econ-project-templates#75]
Right now paths in Latex need to be defined relative to the bld/src/paper (?) directory.
This also entails that the Latex files cannot be compiled outside of waf.

Thus, it may be convenient to allow relative paths from the src/paper/ directory in Latex.

For figures, this should be easy enough by using the ```\graphicspath{}``` command from the graphicx package.

By building on the logic of this package, one could set input paths according to this Stack Exchange post.

https://tex.stackexchange.com/questions/79058/can-a-default-path-be-set-globally-for-input-akin-to-graphicspath

**Comment by hmgaudecker** [comment]
There is a tradeoff here. The LaTeX scanner will not find the dependencies anymore (last time I checked, that is). And I did not see how to specify dependencies manually for the tex builder. Also, I believe Waf gets confused if it finds the same file (output.pdf) in both the src and the bld directory.

I thus opted for the current side of things, so far. But I shall be happy to be convinced otherwise.

**Comment by raholler** [comment]
Ich probier das mal in meinen eigenen Projekten aus. Wenn ich es zum laufen bekomme, würde ich es implementieren.

**Comment by raholler** [comment]
So I tried it, and it at least generates the pdf. The question for me is, what did you expect to fail?

**Comment by hmgaudecker** [comment]
It works on the first run you mean?

My point is that last time I checked, Waf will not realise that some-pdf-on-graphicspath is a dependency and that it will not recompile.

Second problem is that Waf may get confused by a [your-paper].pdf that gets put in the source directory by your favourite compilation tool.

**Comment by raholler** [comment]
You spot on with the first problem, but I do not seem to have the second problem... everything runs fine, even if I have  a pdf in src/paper.

I will try whether the first issue persists when specifiying the paths relative to the bld/paper but in addition adding ../../bld/paper to the latex paths.

**Comment by hmgaudecker** [comment]
> but I do not seem to have the second problem... everything runs fine, even if I have a pdf in src/paper.

More precisely, Waf's checks whether another pass of `pdflatex` (or the like) is needed gets confused by the presence of `aux`-files etc.. Seems like Waf will use those in the `src` folder for checking whether they have changed and of course they have not...

**Comment by hmgaudecker** [comment]
Thanks to pytask, this should not be an issue anymore, I think. 

Probably it cannot handle `\graphicspath`, but it should be okay to compile from Editor.
