### ISSUE TITLE
Couple of minor updates

### ISSUE THREAD

**Issue by hmgaudecker** [OpenSourceEconomics/econ-project-templates#77]
- [x] Document python_version [3.7] in the side-by-side guide
- [x] Check whether anything else is missing or in wrong order
- [x] Fix link in docs for cookiecutter-replay: Should be `econ-project-templates-0.3.2.json` (note the missing **v**.
- [x] Update Azure pipelines for new URL (~@hmgaudecker~ @tobiasraabe )
- [x] Make a release so that URL links are updated in the zip files.
- [x] Search and replace for outdated docs links: hmgaudecker.github.io (e.g., introduction.rst)
- [x] This is probably unnecessary / need updated link to installation instructions: "This assumes you have completed the steps in the README.md file and everything worked."

**Comment by raholler** [comment]
I do not fully understand the last point, could you be a bit more elaborate?

**Comment by hmgaudecker** [comment]
Not much has changed that would merit a release. But the links in the zip files still point to my account, not OpenSourceEconomics. So we should do a 0.3.3 just because of that.

**Comment by hmgaudecker** [comment]
(zip is what cookiecutter downloads)
