### ISSUE TITLE
With multiple waf projects, DAG gets created in the wrong one

### ISSUE THREAD

**Issue by felixpoege** [OpenSourceEconomics/econ-project-templates#78]
I had another waf-based project in my PYTHONPATH and when I was trying to find the DAG (cool addition btw!) of the Stata example, it wasn't in the out/figures/ directory. After I added view=True to the dag.render call in project_dependency_graph.py / make_project_dependency_graph, I could see that the file was indeed created but in the wrong waf project. After purging the PYTHONPATH and only retaining the current project, it gets created in the correct place. It's weird as all the other files are created in the correct place. Not a big deal but maybe good to know. :-)

**Comment by hmgaudecker** [comment]
Thanks for noting this. This seems very hard to track down. 

The general message is: Just never mess with your system-wide PYTHONPATH. It is okay to do so locally in a reproducible way (e.g., the way we do it in `run_py_script`), but changing it system-wide leads to global state that you have to keep in mind.
