### ISSUE TITLE
External dependency?

### ISSUE THREAD

**Issue by felixpoege** [OpenSourceEconomics/econ-project-templates#79]
I want to reference a dependency outside the waf environment (created by an external, ongoing project part). However, if I in `src/wscript` in `set_project_paths` add `pp["IN_EXTERNAL"] = "../abc/"`, it throws the message
`Could not find dependency '..\\..\\..\\__root__\\C\\Data\\path\\to\\resource\\abc\\resource.txt' for running 'src\\data_management\\import\\read_import.py'` although the path C:/Data/path/to/resource/abc/resource.txt exists.

Any advice on how I could specify the external dependency correctly?

**Comment by hmgaudecker** [comment]
Waf does not support this, all has to be in the directory tree. If this is data that is too large to fit on disk twice, you could maybe work with symlinks. Otherwise, it is always useful to keep projects self-contained.
