### ISSUE TITLE
LaTeX does not process all references correctly

### ISSUE THREAD

**Issue by felixpoege** [OpenSourceEconomics/econ-project-templates#80]
Some references within LaTeX, especially to sections, are not processed properly in the waf execution pipeline (with results like `Section ?? briefly introduces the related literature. Section ?? introduces the data sources.`). Links to tables and figures work.
However, when I copy the LaTeX file to the bld/src/paper/ folder and compile manually, even the section references get built correctly. With manually, I mean executing pdflatex -> biber -> pdflatex -> pdflatex in the console in the bld/src/paper/ folder.

Maybe waf is not calling pdflatex again after executing biblatex/biber.. often enough?  Inserting additional calls to self.call_latex() in /.mywaflib/waflib/Tools/tex.py did not solve the problem. After including these lines in the preamble, waf at least calls pdflatex -> biber -> pdflatex -> pdflatex, but the references are still broken
`\AtBeginDocument{\toggletrue{blx@useprefix}}
\AtBeginBibliography{\togglefalse{blx@useprefix}}`

Since I cannot reproduce the issue with the barebone research_paper.tex template from the original project, there should be some LaTeX import conflicting with waf, but I can't figure it out. Is this a known issue of some LaTeX package? I include my full preamble below for reference ... by now, I removed everything that is not required, I hope. https://pastebin.com/KyHnuyFj

(Sorry to send another usage issue, but I'm really stuck on that one)

**Comment by hmgaudecker** [comment]
Thanks. Would you, by any chance, have some LaTeX compilation garbage in the src directory tree? Sometimes waf gets confused by these files...

**Comment by felixpoege** [comment]
Exactly the solution, thank you!
