### ISSUE TITLE
Documentation: Use python3 command on macOS

### ISSUE THREAD

**Issue by mkostmann** [OpenSourceEconomics/econ-project-templates#84]
Using the command `python` (as suggested [here](https://econ-project-templates.readthedocs.io/en/stable/getting_started.html#configuring-your-new-project) in Step 5) on a Mac results in an error:
> Waf: The wscript in '/Users/XXX/projects/map' is unreadable

Instead the command `python3` should be used.

**Comment by hmgaudecker** [comment]
Thanks! In principle, this should not happen [after installing Anaconda](https://econ-project-templates.readthedocs.io/en/stable/getting_started.html#preparing-your-system)-- did you do that and restart the shell?

**Comment by mkostmann** [comment]
Thanks for the quick reply! Using the cone environment solves the problem. I still had to install graphviz and numpy.
