### ISSUE TITLE
General Documentation Updates

### ISSUE THREAD

**Issue by hmgaudecker** [OpenSourceEconomics/econ-project-templates#91]
List of things that need to be updated and/or worked on in the documentation:

- [x] Work through comments in the documentation placed by Maxie in #102 
- [x] Add language-specific pytask / directory sections
- [x] Add how to get started on second machine / collaborator 
      - no need for cookiecutter
      
      git clone ...
      cd [project]
      conda env create
      pre-commit install

**Comment by timmens** [comment]
Done with #98 .
