### ISSUE TITLE
Automate documentation build process

### ISSUE THREAD

**Issue by timmens** [OpenSourceEconomics/econ-project-templates#94]
### 1. Automation

Some parts of the documentation are not build automatically:

- Folder ``econ-project-templates/docs/bld/example/python/python_example``
- Figures in ``econ-project-templates/docs/bld/example/{python, r}``

Is it possible to build them using pytask?

### 2. For Developers Section

The "For Developers" section in the documentation is outdated and needs to be updated. If 1. is not possible, the documenation needs to include a section on manually creating and transferring these files and folders.

**Comment by hmgaudecker** [comment]
> Is it possible to build them using pytask?

We can just call cookiecutter from pytask, I guess. Should not be hard, see the pytest-cookies examples.

**Comment by timmens** [comment]
Implemented in #111. Now one can call ``make html`` to automatically run the figure creation with pytask before the documentation is built.
